library(robotstxt)
path<-paths_allowed("https://www.careerpower.in/cricket-world-cup-winners-list.html")
library(rvest)
link<-"https://www.careerpower.in/cricket-world-cup-winners-list.html"
web<-read_html(link)
library(dplyr)
match_year<-web%>%html_nodes("tr+ tr td:nth-child(1) strong , div:nth-child(7) tr~ tr+ tr td:nth-child(1)")%>%html_text()
View(match_year)
match_host<-web%>%html_nodes("div:nth-child(7) td:nth-child(2)")%>%html_text()
View(match_host)
match_winner<-web%>%html_nodes("div:nth-child(7) td:nth-child(3)")%>%html_text()
View(match_winner)
match_runnerup<-web%>%html_nodes("div:nth-child(7) td:nth-child(5)")%>%html_text()
View(match_runnerup)
Match_database<-data.frame(match_year,match_host,match_winner,match_runnerup)
write.csv(Match_database,"My_match.csv")
